### ISSUE TITLE
Add Alovoa as a viable open-source option for dating apps

### ISSUE THREAD

**Issue by An-anonymous-coder** [MMachado05/floss-alternatives#1]
[Alovoa](https://alovoa.com/) is an open source dating service, with source code found [here](https://github.com/Alovoa/alovoa).

I also maintain my own list of open source software called [Open Source Everything](https://github.com/An-anonymous-coder/Open-Source-Everything), if that helps you out any.

**Comment by MMachado05** [comment]
I was under the impression that was a dead project; good to see it has commits as recent as yesterday! Added now. 👍
